# Generated by Django 5.1.2 on 2024-11-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='stocks.companyinfo'),
        ),
        migrations.AlterModelTable(
            name='companyinfo',
            table=None,
        ),
    ]
