# Generated by Django 5.1.2 on 2024-11-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_company_info_alter_companyinfo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='marketdata',
            name='price_data',
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stocks.company'),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_data', to='stocks.company'),
        ),
    ]
