# Generated by Django 5.1.2 on 2024-11-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_article_articles_remove_marketdata_price_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='data',
        ),
        migrations.AddField(
            model_name='report',
            name='net_income',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='report',
            name='operating_income',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='report',
            name='total_revenue',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='price_data', to='stocks.company'),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(max_length=100),
        ),
    ]
