# Generated by Django 5.1.2 on 2024-11-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_report_data_report_net_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='net_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='operating_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_revenue',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
